IF (OPENSCENEGRAPH_FOUND)

FOREACH(LINKLIB ${OPENSCENEGRAPH_LIBRARIES}) 
target_link_libraries(${prjname} ${LINKLIB})
MESSAGE (STATUS "OpenSceneGraph Libraries: ${LINKLIB}")
ENDFOREACH(LINKLIB)

ENDIF()
