IF (NOT XSD_FOUND)
FIND_PACKAGE(XSD REQUIRED)
include_directories( ${XSD_INCLUDE_DIR} )
ENDIF( NOT XSD_FOUND )

IF( NOT XSD_FOUND )
  MESSAGE( SEND_ERROR "xsd is mandatory" )
ENDIF( NOT XSD_FOUND )

