IF (NOT OSGEARTH_FOUND)
FIND_PACKAGE(OSGEARTH REQUIRED)
include_directories( ${OSGEARTH_INCLUDE_PATH} )
ENDIF( NOT OSGEARTH_FOUND )

IF( NOT OSGEARTH_FOUND )
  MESSAGE( SEND_ERROR "OSGEARTH is mandatory" )
ENDIF( NOT OSGEARTH_FOUND )

