IF (NOT LOG4CXX_FOUND)
FIND_PACKAGE(LOG4CXX REQUIRED)
include_directories( ${LOG4CXX_INCLUDE_DIR} )
ENDIF( NOT LOG4CXX_FOUND )

IF( NOT LOG4CXX_FOUND )
  MESSAGE( SEND_ERROR "log4cxx is mandatory" )
ENDIF( NOT LOG4CXX_FOUND )

