

IF (NOT ACE_FOUND)
FIND_PACKAGE(ACE REQUIRED)
include_directories( ${ACE_INCLUDE_DIRECTORIES} )
ENDIF( NOT ACE_FOUND)

IF( NOT ACE_FOUND )
  MESSAGE( SEND_ERROR "ACE is mandatory" )
ENDIF(NOT ACE_FOUND )

