IF (NOT CRYPTO_FOUND)
FIND_PACKAGE(CRYPTO REQUIRED)
include_directories( ${CRYPTO_INCLUDE_PATH} )
ENDIF( NOT CRYPTO_FOUND )

IF( NOT CRYPTO_FOUND )
  MESSAGE( SEND_ERROR "CRYPTO is mandatory" )
ENDIF( NOT CRYPTO_FOUND )

