IF (NOT TELAREV_FOUND)
FIND_PACKAGE(TELAREV REQUIRED)
include_directories( ${TELAREV_INCLUDE_PATH} )
ENDIF( NOT TELAREV_FOUND )

IF( NOT TELAREV_FOUND )
  MESSAGE( SEND_ERROR "TELAREV is mandatory" )
ENDIF( NOT TELAREV_FOUND )

