IF (NOT NTREE_FOUND)
FIND_PACKAGE(NTREE REQUIRED)
include_directories( ${NTREE_INCLUDE_PATH} )
ENDIF( NOT NTREE_FOUND )

IF( NOT NTREE_FOUND )
  MESSAGE( SEND_ERROR "NTREE is mandatory" )
ENDIF( NOT NTREE_FOUND )

