IF (NOT PYTHON_FOUND)
FIND_PACKAGE(PYTHON REQUIRED)
include_directories( ${PYTHON_INCLUDE_DIR} )
ENDIF( NOT PYTHON_FOUND)

IF( NOT PYTHON_FOUND )
  MESSAGE( SEND_ERROR "python is mandatory" )
ENDIF(NOT PYTHON_FOUND )

