IF (NOT IRCCLIENT_FOUND)
FIND_PACKAGE(IRCCLIENT REQUIRED)
include_directories( ${IRCCLIENT_INCLUDE_DIR} )
ENDIF( NOT IRCCLIENT_FOUND )

IF( NOT IRCCLIENT_FOUND )
  MESSAGE( SEND_ERROR "IRCCLIENT is mandatory" )
ENDIF( NOT IRCCLIENT_FOUND )

