IF (NOT SUNDIALS_FOUND)
FIND_PACKAGE(Sundials REQUIRED)
include_directories( ${SUNDIALS_INCLUDE_DIR})
ENDIF( NOT SUNDIALS_FOUND )

IF( NOT SUNDIALS_FOUND )
  MESSAGE( SEND_ERROR "sundials is mandatory" )
ENDIF( NOT SUNDIALS_FOUND )

