IF (NOT IOBD_FOUND)
FIND_PACKAGE(IOBD REQUIRED)
include_directories( ${IOBD_INCLUDE_DIR} )
ENDIF( NOT IOBD_FOUND )

IF( NOT IOBD_FOUND )
  MESSAGE( SEND_ERROR "iobd is mandatory" )
ENDIF( NOT IOBD_FOUND )

