IF (NOT TELAR_FOUND)
FIND_PACKAGE(TELAR REQUIRED)
include_directories( ${TELAR_INCLUDE_PATH} )
ENDIF( NOT TELAR_FOUND )

IF( NOT TELAR_FOUND )
  MESSAGE( SEND_ERROR "TELAR is mandatory" )
ENDIF( NOT TELAR_FOUND )

