IF (NOT JPEG_FOUND)
FIND_PACKAGE(JPEG REQUIRED)
include_directories( ${JPEG_INCLUDE_DIR} )
ENDIF( NOT JPEG_FOUND )

IF( NOT JPEG_FOUND )
  MESSAGE( SEND_ERROR "JPEG is mandatory" )
ENDIF( NOT JPEG_FOUND )

