IF (NOT ACTIVEMQ_FOUND)
FIND_PACKAGE(ACTIVEMQ REQUIRED)
include_directories( ${ACTIVEMQ_INCLUDE_DIR} )
ENDIF( NOT ACTIVEMQ_FOUND )

IF( NOT ACTIVEMQ_FOUND )
  MESSAGE( SEND_ERROR "ACTIVEMQ is mandatory" )
ENDIF( NOT ACTIVEMQ_FOUND )

