
IF (NOT RTIDDS_FOUND)
FIND_PACKAGE(RTIDDS REQUIRED)
include_directories( ${RTIDDS_INCLUDE_DIRECTORIES} )
IF(UNIX)
add_definitions(-DRTI_UNIX)
add_definitions(-DRTI_LINUX)
ENDIF(UNIX)

ENDIF( NOT RTIDDS_FOUND)

IF( NOT RTIDDS_FOUND )
  MESSAGE( SEND_ERROR "RTIDDS is mandatory" )
ENDIF(NOT RTIDDS_FOUND )

