IF (NOT TALIB_FOUND)
FIND_PACKAGE(TALIB REQUIRED)
include_directories( ${TALIB_INCLUDE_DIR} )
ENDIF( NOT TALIB_FOUND )

IF( NOT TALIB_FOUND )
  MESSAGE( SEND_ERROR "TALIB is mandatory" )
ENDIF( NOT TALIB_FOUND )

