IF (NOT OSGGAUGE_FOUND)
FIND_PACKAGE(OSGGAUGE REQUIRED)
include_directories( ${OSGGAUGE_INCLUDE_PATH} )
ENDIF( NOT OSGGAUGE_FOUND )

IF( NOT OSGGAUGE_FOUND )
  MESSAGE( SEND_ERROR "OSGGAUGE is mandatory" )
ENDIF( NOT OSGGAUGE_FOUND )

