IF (NOT CURLPP_FOUND)
FIND_PACKAGE(CURLPP REQUIRED)
include_directories( ${CURLPP_INCLUDE_DIR} )
ENDIF( NOT CURLPP_FOUND )

IF( NOT CURLPP_FOUND )
  MESSAGE( SEND_ERROR "CURLPP is mandatory" )
ENDIF( NOT CURLPP_FOUND )

