IF (NOT EVENT_FOUND)
FIND_PACKAGE(EVENT REQUIRED)
include_directories( ${EVENT_INCLUDE_DIR} )
ENDIF( NOT EVENT_FOUND )

IF( NOT EVENT_FOUND )
  MESSAGE( SEND_ERROR "EVENT is mandatory" )
ENDIF( NOT EVENT_FOUND )

