IF (NOT MINIUPNPC_FOUND)
FIND_PACKAGE(MINIUPNPC REQUIRED)
include_directories( ${MINIUPNPC_INCLUDE_DIR} )
ENDIF( NOT MINIUPNPC_FOUND )

IF( NOT MINIUPNPC_FOUND )
  MESSAGE( SEND_ERROR "MINIUPNPC is mandatory" )
ENDIF( NOT MINIUPNPC_FOUND )

