IF (NOT PYTHON3_FOUND)
FIND_PACKAGE(PYTHON3 REQUIRED)
add_definitions( ${PYTHON3_CFLAGS} )
ENDIF( NOT PYTHON3_FOUND)

IF( NOT PYTHON3_FOUND )
  MESSAGE( SEND_ERROR "python3 is mandatory" )
ENDIF(NOT PYTHON3_FOUND )

