IF (NOT JSONCPP_FOUND)
FIND_PACKAGE(JSONCPP REQUIRED)
include_directories( ${JSONCPP_INCLUDE_DIR} )
ENDIF( NOT JSONCPP_FOUND )

IF( NOT JSONCPP_FOUND )
  MESSAGE( SEND_ERROR "JSONCPP is mandatory" )
ENDIF( NOT JSONCPP_FOUND )

