IF (NOT MODULE_3D_GEO_VIEWER_FOUND)
FIND_PACKAGE(MOD3DGEOVIEWER REQUIRED)
include_directories( ${MODULE_3D_GEO_VIEWER_INCLUDE_PATH} )
ENDIF( NOT MODULE_3D_GEO_VIEWER_FOUND )

IF( NOT MODULE_3D_GEO_VIEWER_FOUND )
  MESSAGE( SEND_ERROR "MOD3DGEOVIEWER is mandatory" )
ENDIF( NOT MODULE_3D_GEO_VIEWER_FOUND )

