
IF (NOT LIBXMLPP_FOUND)
FIND_PACKAGE(LibXmlPP REQUIRED)
include_directories( ${LIBXMLPP_INCLUDE_DIR} )
ENDIF( NOT LIBXMLPP_FOUND )

IF( NOT LIBXMLPP_FOUND )
  MESSAGE( SEND_ERROR "libxml++ is mandatory" )
ENDIF(NOT LIBXMLPP_FOUND )

