IF (NOT UUID_FOUND)
FIND_PACKAGE(UUID REQUIRED)
include_directories( ${UUID_INCLUDE_PATH} )
ENDIF( NOT UUID_FOUND )

IF( NOT UUID_FOUND )
  MESSAGE( SEND_ERROR "UUID is mandatory" )
ENDIF( NOT UUID_FOUND )

