IF (NOT OPENSCENEGRAPH_FOUND)
FIND_PACKAGE(OpenSceneGraph REQUIRED osg osgDB osgFX osgGA osgSim osgText osgViewer osgParticle)
include_directories( ${OPENSCENEGRAPH_INCLUDE_DIRS} )
MESSAGE (STATUS "INCLUDE DIR ${OPENSCENEGRAPH_INCLUDE_DIRS}")
ENDIF( NOT OPENSCENEGRAPH_FOUND )

IF( NOT OPENSCENEGRAPH_FOUND )
  MESSAGE( SEND_ERROR "OSG is mandatory" )
ENDIF( NOT OPENSCENEGRAPH_FOUND )

