Document: mmmake
Title: Debian mmmake Manual
Author: Marcos Mayorga
Abstract: This manual describes what mmmake is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mmmake/mmmake.sgml.gz

Format: postscript
Files: /usr/share/doc/mmmake/mmmake.ps.gz

Format: text
Files: /usr/share/doc/mmmake/mmmake.text.gz

Format: HTML
Index: /usr/share/doc/mmmake/html/index.html
Files: /usr/share/doc/mmmake/html/*.html
