IF (NOT SERIAL_FOUND)

FIND_PATH(SERIAL_INCLUDE_DIR SerialStream.h
  /usr/include
  /usr/local/include/
  DOC "Directory containing serial headers"
)

SET(LIBSEARCHPATHS 
	/usr/lib
	/usr/local/lib
) 

FIND_LIBRARY(SERIAL_LIBRARY
	NAMES
		serial
	PATHS 	${LIBSEARCHPATHS} 
) 

FIND_LIBRARY(SERIAL_LIBRARY_D
	NAMES 	
		serial
	PATHS 	${LIBSEARCHPATHS}
) 


IF (SERIAL_INCLUDE_DIR AND SERIAL_LIBRARY_D AND SERIAL_LIBRARY)
	SET(SERIAL_FOUND TRUE) 
ENDIF (SERIAL_INCLUDE_DIR AND SERIAL_LIBRARY_D AND SERIAL_LIBRARY)

IF (SERIAL_FOUND)
	IF (NOT Serial_FIND_QUIETLY) 
		MESSAGE(STATUS "Found Serial: ${SERIAL_LIBRARY}") 
	ENDIF (NOT Serial_FIND_QUIETLY) 
ELSE (SERIAL_FOUND)
	 IF (Serial_FIND_REQUIRED) 
		MESSAGE(FATAL_ERROR "Could not find Serial") 
	ENDIF (Serial_FIND_REQUIRED) 
ENDIF (SERIAL_FOUND)

ENDIF (NOT SERIAL_FOUND)
