IF (NOT XPLANE_FOUND)

FIND_PATH(XPLANE_INCLUDE_DIR xplane/XPLM/XPLMGraphics.h
  c:/xplane-8.64/include  
  /usr/include
  /usr/local/include
  DOC "Directory containing x-plane headers"
)

SET(LIBSEARCHPATHS 
	/usr/local/lib
      c:/xplane-8.64/lib
	/usr/lib
	R:/usr/lib
	${DISTR_PREFIX}/lib
) 

if (UNIX)
	SET(NEED_XPLANE_LIBRARY OFF)
	SET(XPLANE_LIBRARY )
	IF (XPLANE_INCLUDE_DIR)
		SET(XPLANE_FOUND TRUE) 
	ENDIF (XPLANE_INCLUDE_DIR)

	IF (XPLANE_FOUND)
		IF (NOT XPLANE_FIND_QUIETLY) 
			MESSAGE(STATUS "Found XPLANE: ${XPLANE_INCLUDE_DIR}") 
		ENDIF (NOT XPLANE_FIND_QUIETLY) 
	ELSE (XPLANE_FOUND)
		 IF (XPLANE_FIND_REQUIRED) 
			MESSAGE(FATAL_ERROR "Could not find XPLANE") 
		ENDIF (XPLANE_FIND_REQUIRED) 
	ENDIF (XPLANE_FOUND)

else (UNIX)
	SET(NEED_XPLANE_LIBRARY ON)

	FIND_LIBRARY(XPLANE_LIBRARY
		NAMES
			XPLM
			XPLM.so
		PATHS 	${LIBSEARCHPATHS} 
	) 
	IF (XPLANE_INCLUDE_DIR AND XPLANE_LIBRARY)
		SET(XPLANE_FOUND TRUE) 
	ENDIF (XPLANE_INCLUDE_DIR AND XPLANE_LIBRARY)
	
	IF (XPLANE_FOUND)
		IF (NOT XPLANE_FIND_QUIETLY) 
			MESSAGE(STATUS "Found XPLANE: ${XPLANE_LIBRARY}") 
		ENDIF (NOT XPLANE_FIND_QUIETLY) 
	ELSE (XPLANE_FOUND)
		 IF (XPLANE_FIND_REQUIRED) 
			MESSAGE(FATAL_ERROR "Could not find XPLANE") 
		ENDIF (XPLANE_FIND_REQUIRED) 
	ENDIF (XPLANE_FOUND)

endif (UNIX)



ENDIF (NOT XPLANE_FOUND)
