IF (NOT XSD_FOUND)

FIND_PATH(XSD_INCLUDE_DIR auto-array.hxx
    /usr/include/xsd/cxx
    /usr/local/include/xsd/cxx
)

IF (XSD_INCLUDE_DIR)
	SET(XSD_FOUND TRUE) 
ENDIF (XSD_INCLUDE_DIR)

IF (XSD_FOUND)
	IF (NOT XSD_FIND_QUIETLY) 
		MESSAGE(STATUS "Found XSD: ${XSD_INCLUDE_DIR}") 
	ENDIF (NOT XSD_FIND_QUIETLY) 
ELSE (XSD_FOUND)
	 IF (XSD_FIND_REQUIRED) 
		MESSAGE(FATAL_ERROR "Could not find XSD") 
	ENDIF (XSD_FIND_REQUIRED) 
ENDIF (XSD_FOUND)

ENDIF (NOT XSD_FOUND)
