IF (NOT XPLAIN_FOUND)

FIND_PATH(XPLAIN_INCLUDE_DIR xplain/XPLMGraphics.h
  /usr/local/include
  /usr/include
  DOC "Directory containing xplain headers (X-Plane 9)"
)

SET(LIBSEARCHPATHS 
	/usr/local/lib
  	/usr/lib
	${DISTR_PREFIX}/lib
) 

if (UNIX)
	SET(NEED_XPLAIN_LIBRARY OFF)
	SET(XPLAIN_LIBRARY )
	IF (XPLAIN_INCLUDE_DIR)
		SET(XPLAIN_FOUND TRUE) 
	ENDIF (XPLAIN_INCLUDE_DIR)

	IF (XPLAIN_FOUND)
		IF (NOT XPLAIN_FIND_QUIETLY) 
			MESSAGE(STATUS "Found XPLAIN: ${XPLAIN_INCLUDE_DIR}") 
		ENDIF (NOT XPLAIN_FIND_QUIETLY) 
	ELSE (XPLAIN_FOUND)
		 IF (XPLAIN_FIND_REQUIRED) 
			MESSAGE(FATAL_ERROR "Could not find XPLAIN") 
		ENDIF (XPLAIN_FIND_REQUIRED) 
	ENDIF (XPLAIN_FOUND)

else (UNIX)
	SET(NEED_XPLAIN_LIBRARY ON)

	FIND_LIBRARY(XPLAIN_LIBRARY
		NAMES
			XPLM
			XPLM.so
		PATHS 	${LIBSEARCHPATHS} 
	) 
	IF (XPLAIN_INCLUDE_DIR AND XPLAIN_LIBRARY)
		SET(XPLAIN_FOUND TRUE) 
	ENDIF (XPLAIN_INCLUDE_DIR AND XPLAIN_LIBRARY)
	
	IF (XPLAIN_FOUND)
		IF (NOT XPLAIN_FIND_QUIETLY) 
			MESSAGE(STATUS "Found XPLAIN: ${XPLAIN_LIBRARY}") 
		ENDIF (NOT XPLAIN_FIND_QUIETLY) 
	ELSE (XPLAIN_FOUND)
		 IF (XPLAIN_FIND_REQUIRED) 
			MESSAGE(FATAL_ERROR "Could not find XPLAIN") 
		ENDIF (XPLAIN_FIND_REQUIRED) 
	ENDIF (XPLAIN_FOUND)

endif (UNIX)



ENDIF (NOT XPLAIN_FOUND)
