IF (NOT CRYPTOPP_FOUND)

FIND_PATH(CRYPTOPP_INCLUDE_PATH crypto++/sha.h
  /usr/include
  /usr/local/include

  DOC "Directory containing CRYPTO++ headers"
)


FIND_LIBRARY( CRYPTOPP_LIBRARY
  NAMES cryptopp
  PATHS /usr/lib
        /usr/local/lib
        /usr/lib/${MMMAKE_TRIPLET}
)


SET(CRYPTOPP_LIBRARIES ${CRYPTOPP_LIBRARY})


IF (CRYPTOPP_INCLUDE_PATH AND CRYPTOPP_LIBRARY)
	SET(CRYPTOPP_FOUND TRUE) 
ENDIF ()

IF (CRYPTOPP_FOUND)
	IF (NOT CRYPTOPP_FIND_QUIETLY) 
		MESSAGE(STATUS "Found CRYPTO++: ${CRYPTOPP_LIBRARY}") 
	ENDIF (NOT CRYPTOPP_FIND_QUIETLY) 
ELSE (CRYPTOPP_FOUND)
	IF (CRYPTOPP_FIND_REQUIRED) 
		MESSAGE(FATAL_ERROR "Could not find CRYPTO++") 
	ENDIF (CRYPTOPP_FIND_REQUIRED) 
ENDIF (CRYPTOPP_FOUND)

ENDIF ()
