IF (NOT MINIUPNPC_FOUND)

FIND_PATH(MINIUPNPC_ROOT_DIR miniupnpc/miniupnpc.h
	PATHS
	/usr
	/usr/local
	c:/
	PATH_SUFFIXES include
	DOC "Directory containing MINIUPNPC headers"
)

IF (MINIUPNPC_ROOT_DIR)
	SET(MINIUPNPC_FOUND TRUE) 
ENDIF (MINIUPNPC_ROOT_DIR)

IF (MINIUPNPC_FOUND)

FIND_LIBRARY( MINIUPNPC_LIBRARY
  NAMES miniupnpc
  PATHS /usr/lib
        /usr/local/lib
	/usr/lib/${MMMAKE_TRIPLET}
)


	SET(MINIUPNPC_LIBRARIES ${MINIUPNPC_LIBRARY})
	SET(MINIUPNPC_INCLUDE_DIR ${MINIUPNPC_ROOT_DIR} )
	MESSAGE(STATUS "Found MINIUPNPC: ${MINIUPNPC_ROOT_DIR} ${MINIUPNPC_LIBRARIES}") 

ELSE (MINIUPNPC_FOUND)
	MESSAGE(FATAL_ERROR "Could not find MINIUPNPC. apt install libminiupnpc-dev") 
ENDIF (MINIUPNPC_FOUND)

ENDIF (NOT MINIUPNPC_FOUND)

