IF (NOT LOG4CXX_FOUND)

FIND_PATH(LOG4CXX_INCLUDE_DIR logger.h
  /usr/include/log4cxx/
  DOC "Directory containing log4cxx headers"
)

SET(LIBSEARCHPATHS 
    $ENV{LD_LIBRARY_PATH}
) 


FIND_LIBRARY(LOG4CXX_LIBRARY
	NAMES
		log4cxx
	PATHS 	${LIBSEARCHPATHS} 
) 

FIND_LIBRARY(LOG4CXX_LIBRARY_D
	NAMES 	
		log4cxx
	PATHS 	${LIBSEARCHPATHS}
) 

IF (LOG4CXX_INCLUDE_DIR AND LOG4CXX_LIBRARY_D AND LOG4CXX_LIBRARY)
	SET(LOG4CXX_FOUND TRUE) 
ENDIF (LOG4CXX_INCLUDE_DIR AND LOG4CXX_LIBRARY_D AND LOG4CXX_LIBRARY)

IF (LOG4CXX_FOUND)
	IF (NOT LOG4CXX_FIND_QUIETLY) 
		MESSAGE(STATUS "Found log4cxx: ${LOG4CXX_LIBRARY}") 
	ENDIF (NOT LOG4CXX_FIND_QUIETLY) 
ELSE (LOG4CXX_FOUND)
	 IF (LOG4CXX_FIND_REQUIRED) 
		MESSAGE(FATAL_ERROR "Could not find log4cxx") 
	ENDIF (LOG4CXX_FIND_REQUIRED) 
ENDIF (LOG4CXX_FOUND)

ENDIF (NOT LOG4CXX_FOUND)
