IF (NOT ACTIVEMQ_FOUND)

FIND_PATH(ACTIVEMQ_INCLUDE_DIR decaf
  $ENV{ACTIVEMQ_CPP_ROOT}
  $ENV{ACTIVEMQ_CPP_ROOT}/src/main/
  /usr/local/include/activemq-cpp-3.1.2/
  /usr/local/include/activemq-cpp-2.2.6/
  /usr/local/include/activemq-cpp-2.2.5/
  DOC "Directory containing activemq headers"
)

SET(LIBSEARCHPATHS 
    $ENV{ACTIVEMQ_CPP_ROOT}/.libs/
    $ENV{ACTIVEMQ_CPP_ROOT}/src/main/.libs/
    $ENV{LD_LIBRARY_PATH}
) 


FIND_LIBRARY(ACTIVEMQ_LIBRARY
	NAMES
		activemq-cpp
	PATHS 	${LIBSEARCHPATHS} 
) 

FIND_LIBRARY(ACTIVEMQ_LIBRARY_D
	NAMES 	
		activemq-cpp
	PATHS 	${LIBSEARCHPATHS}
) 

IF (ACTIVEMQ_INCLUDE_DIR AND ACTIVEMQ_LIBRARY_D AND ACTIVEMQ_LIBRARY)
	SET(ACTIVEMQ_FOUND TRUE) 
ENDIF (ACTIVEMQ_INCLUDE_DIR AND ACTIVEMQ_LIBRARY_D AND ACTIVEMQ_LIBRARY)

IF (ACTIVEMQ_FOUND)
	IF (NOT ActiveMQ_FIND_QUIETLY) 
		MESSAGE(STATUS "Found ActiveMQ: ${ACTIVEMQ_LIBRARY}") 
	ENDIF (NOT ActiveMQ_FIND_QUIETLY) 
ELSE (ACTIVEMQ_FOUND)
	 IF (ActiveMQ_FIND_REQUIRED) 
		MESSAGE(FATAL_ERROR "Could not find ActiveMQ") 
	ENDIF (ActiveMQ_FIND_REQUIRED) 
ENDIF (ACTIVEMQ_FOUND)

ENDIF (NOT ACTIVEMQ_FOUND)
