IF (NOT MODULE_PL_CAMERA_FOUND)

FIND_PATH(MODULE_PL_CAMERA_INCLUDE_PATH modules/payloads/plcamera/moduleplcamera.h
  /usr/include
  /usr/local/include
  DOC "Directory containing PL Camera module headers"
) 


FIND_LIBRARY( MODULE_PL_CAMERA_LIBRARY
  NAMES moduleplcamera
  PATHS /usr/lib
        /usr/local/lib
)

FIND_LIBRARY( MODULE_PL_CAMERA_PRTL_LIBRARY
  NAMES moduleplcamera_prtl
  PATHS /usr/lib
        /usr/local/lib
)


SET(MODULE_PL_CAMERA_LIBRARIES ${MODULE_PL_CAMERA_LIBRARY} ${MODULE_PL_CAMERA_PRTL_LIBRARY})


IF (MODULE_PL_CAMERA_INCLUDE_PATH AND MODULE_PL_CAMERA_LIBRARY AND MODULE_PL_CAMERA_PRTL_LIBRARY)
	SET(MODULE_PL_CAMERA_FOUND TRUE) 
ENDIF ()

IF (MODULE_PL_CAMERA_FOUND)
	IF (NOT MODULE_PL_CAMERA_FIND_QUIETLY) 
		MESSAGE(STATUS "Found MODULE_PL_CAMERA: ${MODULE_PL_CAMERA_LIBRARY}") 
	ENDIF (NOT MODULE_PL_CAMERA_FIND_QUIETLY) 
ELSE (MODULE_PL_CAMERA_FOUND)
	IF (MODULE_PL_CAMERA_FIND_REQUIRED) 
		MESSAGE(FATAL_ERROR "Could not find MODULE_PL_CAMERA") 
	ENDIF (MODULE_PL_CAMERA_FIND_REQUIRED) 
ENDIF (MODULE_PL_CAMERA_FOUND)



ENDIF ()
