IF (NOT UUID_FOUND)

FIND_PATH(UUID_INCLUDE_PATH uuid/uuid.h
  /usr/include
  /usr/local/include
  DOC "Directory containing UUID headers"
) 


FIND_LIBRARY( UUID_LIBRARY
  NAMES uuid
  PATHS /usr/lib
        /usr/local/lib
)




SET(UUID_LIBRARIES ${UUID_LIBRARY})


IF (UUID_INCLUDE_PATH AND UUID_LIBRARY)
	SET(UUID_FOUND TRUE) 
ENDIF ()

IF (UUID_FOUND)
	IF (NOT UUID_FIND_QUIETLY) 
		MESSAGE(STATUS "Found UUID: ${UUID_LIBRARY}") 
	ENDIF (NOT UUID_FIND_QUIETLY) 
ELSE (UUID_FOUND)
	IF (UUID_FIND_REQUIRED) 
		MESSAGE(FATAL_ERROR "Could not find UUID") 
	ENDIF (UUID_FIND_REQUIRED) 
ENDIF (UUID_FOUND)



ENDIF ()
