IF (NOT NTREE_FOUND)

FIND_PATH(NTREE_INCLUDE_PATH ntree/ntree.h
  /usr/include
  /usr/local/include
  DOC "Directory containing NTREE headers"
) 


FIND_LIBRARY( NTREE_LIBRARY
  NAMES ntree
  PATHS /usr/lib
        /usr/local/lib
)

SET(NTREE_LIBRARIES ${NTREE_LIBRARY})


IF (NTREE_INCLUDE_PATH AND NTREE_LIBRARY)
	SET(NTREE_FOUND TRUE) 
ENDIF ()

IF (NTREE_FOUND)
	IF (NOT NTREE_FIND_QUIETLY) 
		MESSAGE(STATUS "Found NTREE: ${NTREE_LIBRARY}") 
	ENDIF (NOT NTREE_FIND_QUIETLY) 
ELSE (NTREE_FOUND)
	IF (NTREE_FIND_REQUIRED) 
		MESSAGE(NTREE_ERROR "Could not find NTREE") 
	ENDIF (NTREE_FIND_REQUIRED) 
ENDIF (NTREE_FOUND)



ENDIF ()
