IF (NOT MODULE_3D_GEO_VIEWER_FOUND)

FIND_PATH(MODULE_3D_GEO_VIEWER_INCLUDE_PATH modules/3d_geoviewer/moduleGeoViewer3D.h
  /usr/include
  /usr/local/include
  DOC "Directory containing 3d Geo Viewer headers"
) 


FIND_LIBRARY( MODULE_3D_GEO_VIEWER_LIBRARY
  NAMES moduleGeoViewer3D
  PATHS /usr/lib
        /usr/local/lib
)

FIND_LIBRARY( MODULE_3D_GEO_VIEWER_PRTL_LIBRARY
  NAMES moduleGeoViewer3D_prtl
  PATHS /usr/lib
        /usr/local/lib
)


SET(MODULE_3D_GEO_VIEWER_LIBRARIES ${MODULE_3D_GEO_VIEWER_LIBRARY} ${MODULE_3D_GEO_VIEWER_PRTL_LIBRARY})


IF (MODULE_3D_GEO_VIEWER_INCLUDE_PATH AND MODULE_3D_GEO_VIEWER_LIBRARY AND MODULE_3D_GEO_VIEWER_PRTL_LIBRARY)
	SET(MODULE_3D_GEO_VIEWER_FOUND TRUE) 
ENDIF ()

IF (MODULE_3D_GEO_VIEWER_FOUND)
	IF (NOT MODULE_3D_GEO_VIEWER_FIND_QUIETLY) 
		MESSAGE(STATUS "Found MODULE_3D_GEO_VIEWER: ${MODULE_3D_GEO_VIEWER_LIBRARY}") 
	ENDIF (NOT MODULE_3D_GEO_VIEWER_FIND_QUIETLY) 
ELSE (MODULE_3D_GEO_VIEWER_FOUND)
	IF (MODULE_3D_GEO_VIEWER_FIND_REQUIRED) 
		MESSAGE(FATAL_ERROR "Could not find MODULE_3D_GEO_VIEWER") 
	ENDIF (MODULE_3D_GEO_VIEWER_FIND_REQUIRED) 
ENDIF (MODULE_3D_GEO_VIEWER_FOUND)



ENDIF ()
